Add a placeholer URDF for the AMP mount
clearpathrobotics/clearpath_common pull request #123
Opened 2024-12-02 18:18 UTC by civerachb-cpr

The AMP frame is undergoing some redesigns right now, so the final dimensions and STL are not available. But this adds a placeholder we can use for developing the software & doing validation of the generator until the final CAD files are available.

2024-12-02 19:23 UTC, civerachb-cpr commented
A300 with placeholder AMP mount + sensors, treaded wheels, updated meshes.

![Screenshot from 2024-12-02 14-22-10](https://github.com/user-attachments/assets/d44adb26-f681-407f-a608-935b9406c106)

2024-12-02 22:03 UTC, luis-camero requested changes

2024-12-02 22:03 UTC, luis-camero commented on clearpath_platform_description/urdf/a300/mobility/diff_drive.urdf.xacro
> +    <xacro:if value="${wheel == 'default' or heel == 'tread'}">
Typo: `heel` should be `wheel`

2024-12-02 22:45 UTC, civerachb-cpr commented on clearpath_platform_description/urdf/a300/mobility/diff_drive.urdf.xacro
> +    <xacro:if value="${wheel == 'default' or heel == 'tread'}">
Whoops. Fixed.

2024-12-03 21:27 UTC, civerachb-cpr commented
Sorry about the commits & reversions; accidentally pushed some sim-related stuff I was working on to the wrong branch.

This should be ready for review & (hopefully) merging now.

2024-12-04 23:46 UTC, luis-camero approved these changes

2024-12-05 18:08 UTC, civerachb-cpr commented
I'm just massaging this to get the Source CI to pass and then I'll merge it.

2024-12-05 18:22 UTC, merged