Block joy teleop inputs if signal quality is poor
clearpathrobotics/clearpath_common pull request #131
Opened 2024-12-16 17:34 UTC by civerachb-cpr

Adds a new `clearpath_bt_joy` package which contains a node that monitors the link quality of the connection to the game controller and uses that to publish a `quality_ok` topic that can be used a lock to a `twist_mux` node.

The joy controller topics & nodes are slightly reworked, with some new hidden topics. Everything remains API compatible with the existing layout.

Previously:
- `joy_linux` publishes `joy_teleop/joy`
- `teleop_twist_joy` subscribes to `joy_teleop/joy`, publishes `joy_teleop/cmd_vel`

Now:
- `joy_linux` still publishes `joy_teleop/joy`
- `joy_linux` publishes `joy_teleop/_/cmd_vel_src` (hidden topic)
- `clearpath_bt_joy` publishes `joy_teleop/quality` and `joy_teleop/quality_ok` as new topics
- a new `twist_mux` subscribes to `joy_teleop/_/cmd_vel_src` as the input and `joy_teleop/quality_ok` as a lock, publishing `joy_teleop/cmd_vel` as the output

By relying on the `bluez` package's `hcitool lq MAC_ADDR` command, we avoid adding any additional systemd jobs or modifying the OS's joy controller drivers; we just passively monitor the link quality and use the `twist_mux`'s lock input to disable the controller input when needed.

## Context
Linux game controllers latch their last-received command for a brief period when the connection to the controller is lost. When dealing with a physical robot this can cause a dangerous situation where the robot is literally untrontrollable for a brief window of time.

Previously we used the DS4DRV package to mitigate this, but that package was specific to the PS4/DualShock controller, which we may be moving away from.

2025-01-06 21:48 UTC, roni-kreinin requested changes
Other than the hidden topics, LGTM

2025-01-06 21:48 UTC, roni-kreinin commented on clearpath_control/launch/teleop_joy.launch.py
> +            ('cmd_vel', 'joy_teleop/_/cmd_vel_src'),
Can we use `joy_teleop/_cmd_vel_src` to match our other hidden topic naming conventions?

For example: https://github.com/clearpathrobotics/clearpath_robot/blob/d240de9a0b058d130a870122e8100d6ab368b2ab/clearpath_hardware_interfaces/src/lighting/lighting.cpp#L204

2025-01-06 21:48 UTC, roni-kreinin commented on clearpath_control/launch/teleop_joy.launch.py
> +            {'topics.joy.topic': 'joy_teleop/_/cmd_vel_src'},
Same thing here

2025-01-06 21:49 UTC, roni-kreinin commented on clearpath_control/launch/teleop_joy.launch.py
> +            ('cmd_vel', 'joy_teleop/_/cmd_vel_src'),
Maybe just call it `joy_teleop/_cmd_vel`

2025-01-06 21:52 UTC, civerachb-cpr commented on clearpath_control/launch/teleop_joy.launch.py
> +            ('cmd_vel', 'joy_teleop/_/cmd_vel_src'),
I can rename the topic, no problem.

2025-01-06 22:03 UTC, civerachb-cpr commented on clearpath_control/launch/teleop_joy.launch.py
> +            ('cmd_vel', 'joy_teleop/_/cmd_vel_src'),
Done.

2025-01-06 22:03 UTC, civerachb-cpr commented on clearpath_control/launch/teleop_joy.launch.py
> +            {'topics.joy.topic': 'joy_teleop/_/cmd_vel_src'},
Done.

2025-01-06 22:17 UTC, hilary-luo requested changes
A couple more high level comments:
- Consider adding some additional info logging lines to show if it is still waiting on something else (ex. a service to be available like line 60 in clearpath_bt_joy_cutoff_node.py) vs it is ready and operational
- Consider whether the quality or timeout should be configurable from the robot.yaml

2025-01-06 22:17 UTC, hilary-luo commented on clearpath_bt_joy/clearpath_bt_joy/clearpath_bt_joy_cutoff_node.py
> +            self.get_logger().warn('Unable to determine joy device')
Shouldn't this be `.warning`?

2025-01-06 22:17 UTC, hilary-luo commented on clearpath_bt_joy/clearpath_bt_joy/clearpath_bt_joy_cutoff_node.py
> +            self.get_logger().warn(f'Unable to determine MAC address for {self.joy_device}')
Same as above (`.warning`)

2025-01-06 22:17 UTC, hilary-luo commented on clearpath_control/launch/teleop_joy.launch.py
> +            {'locks.bt_quality.timeout': 0.0},
This has the quality timeout disabled, it would be "safer" to timeout on a stale quality topic. Let's discuss

2025-01-06 22:17 UTC, hilary-luo commented on clearpath_bt_joy/clearpath_bt_joy/clearpath_bt_joy_cutoff_node.py
> +        - quality_ok  (std_msgs/Bool) -- is the quality good enough to accept the joy inputs?
Should this second topic be `bt_quality_stop`

2025-01-06 22:27 UTC, civerachb-cpr commented on clearpath_control/launch/teleop_joy.launch.py
> +            {'locks.bt_quality.timeout': 0.0},
I've added a 1s timeout after discussing on Slack.

2025-01-06 22:28 UTC, civerachb-cpr commented on clearpath_bt_joy/clearpath_bt_joy/clearpath_bt_joy_cutoff_node.py
> +        - quality_ok  (std_msgs/Bool) -- is the quality good enough to accept the joy inputs?
Correct, it should be. That's a leftover from an earlier revision.

2025-01-06 22:30 UTC, civerachb-cpr commented
Updated the MR description to reflect changes to topic names, just in case we ever refer back to this down the road.

2025-01-07 18:14 UTC, civerachb-cpr commented on clearpath_control/launch/teleop_joy.launch.py
> +            {'locks.bt_quality.timeout': 0.0},
Made a few further changes to the code for non-bluetooth controllers to work around the timeout. Since if the controller doesn't have a MAC it's most likely using a dongle or it's wired, we just publish full quality. If the device is then unplugged it will stop publishing anyway, so the quality cutoff is irrelevant.

2025-01-07 18:15 UTC, civerachb-cpr commented on clearpath_bt_joy/clearpath_bt_joy/clearpath_bt_joy_cutoff_node.py
> +            self.get_logger().warn('Unable to determine joy device')
Yes, that's my ROS 1 instincts taking over. Fixed.

2025-01-14 16:05 UTC, hilary-luo approved these changes
Looks good to me

2025-01-14 16:47 UTC, merged